feature/create user
fzldn/ticketing pull request #29
Opened 2024-05-06 07:18 UTC by rafiaditya11

2024-05-06 07:33 UTC, fzldn requested changes

2024-05-06 07:33 UTC, fzldn commented on resources/views/users/create.blade.php
> +                        </div>
please use new input component `<x-input/>`

2024-05-06 07:33 UTC, fzldn commented on resources/views/users/create.blade.php
> +                        </div>
please use new input component `<x-input/>`

2024-05-06 07:33 UTC, fzldn commented on resources/views/users/create.blade.php
> +                        </div>
please use new input component `<x-input/>`

2024-05-06 07:33 UTC, fzldn commented on resources/views/users/create.blade.php
> +                        </div>
please use new input component `<x-input/>`

2024-05-06 07:33 UTC, fzldn commented on resources/views/users/index.blade.php
> +                </div>
leave it use `<x-input/>`

2024-05-07 03:45 UTC, fzldn requested changes

2024-05-07 03:45 UTC, fzldn commented on resources/views/components/input.blade.php
> +<div {{ $wrapperAttributes() }} class="mt-4">
ga perlu nambahin disini, di input component bisa nambahin `wrapper-class="mt-4"`

```
<x-input wrapper-class="mt-4"/>
```

2024-05-07 03:45 UTC, fzldn commented on resources/views/components/input.blade.php
> +        <label {{ $labelAttributes() }} class="block">
ga perlu nambahin disini di input component bisa nambahin `label-class="block"`

```
<x-input label-class="block"/>
```

2024-05-07 03:45 UTC, fzldn commented on app/View/Components/Input.php
> +            'value' => old($this->name, $this->value),
apa ini changes yg ngga perlu

2024-05-07 03:45 UTC, fzldn commented on resources/views/components/input.blade.php
> +        <input {{ $inputAttributes() }} class="block w-full border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"> <!-- Tambahkan class
ngga perlu nambahin disini, kita bisa tambahin di input component nya klo perlu

```
<x-input class="block w-full border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"/>
```

2024-05-07 03:45 UTC, fzldn commented on app/Http/Controllers/UserController.php
> +    $user->save();
ubah pake `User::create([])`

2024-05-07 04:53 UTC, rafiaditya11 reviewed
maaf om ini tadi ke merge kirainnya ada conflict,tapi udh saya revert

2024-05-07 08:08 UTC, fzldn requested changes

2024-05-07 08:08 UTC, fzldn commented on resources/views/components/input.blade.php
> +        <input {{ $inputAttributes() }}>
ini ada yg ke hapus slash nya

2024-05-07 08:47 UTC, fzldn approved these changes

2024-05-07 08:47 UTC, merged